// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import ()

type Todo struct {
	ID          int32  `json:"id"`
	Todo        string `json:"todo"`
	Description string `json:"description"`
}
